import App from "./app/app.component.js"
import SocialMediaList from "./app/social-media-list/social-media-list.component.js"
import HomeSection from "./app/home-section/home-section.component.js"
import ContentSection from "./app/content-section/content-section.component.js"
import EventList from "./app/event-list/event-list.component.js"
import BandList from "./app/band-list/band-list.component.js"
import DonationList from "./app/donation-list/donation-list.component.js"
import BottomNav from "./app/bottom-nav/bottom-nav.component.js"